/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ordemDeServico.view;


import br.com.ordemDeServico.model.dao.ClienteDao;
import br.com.ordemDeServico.model.entity.Cliente;
import javax.swing.JOptionPane;

/**
 *
 * @author adilson
 */
public class CadastrarCliente extends javax.swing.JFrame {
    private Cliente cliente;
    private ClienteDao daoCliente;
   
    
    
    public CadastrarCliente() {
        initComponents();
        setTitle("Cadastro Cliente");  
        this.daoCliente = new ClienteDao();
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        cadastrarCli = new javax.swing.JButton();
        jTFTelefone = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFCPF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFRG = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel3.setText("Telefone");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 176, -1, -1));

        jTFNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTFNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 387, -1));

        cadastrarCli.setText("Cadastrar");
        cadastrarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarCliActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, -1, -1));
        getContentPane().add(jTFTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 170, 149, -1));

        jLabel5.setText("CPF: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        getContentPane().add(jTFCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 271, -1));

        jLabel2.setText("RG");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 114, -1, -1));
        getContentPane().add(jTFRG, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 106, 271, -1));

        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNomeActionPerformed

    }//GEN-LAST:event_jTFNomeActionPerformed

    private void cadastrarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarCliActionPerformed
       
        cliente =  new Cliente();
        
       
       cliente.setNome(jTFNome.getText());
       cliente.setCpf(jTFCPF.getText());
       cliente.setTelefone(jTFTelefone.getText());
       cliente.setRg(jTFRG.getText());
       daoCliente.insert(cliente);
           
          
       jTFNome.setText(null);
       jTFCPF.setText(null);
       jTFRG.setText(null);
       jTFTelefone.setText(null);
        JOptionPane.showMessageDialog(null, "Cliente cadastrado com Sucesso");
    }//GEN-LAST:event_cadastrarCliActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed
     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarCliente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarCli;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTFCPF;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFRG;
    private javax.swing.JFormattedTextField jTFTelefone;
    // End of variables declaration//GEN-END:variables
}
