/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ofiSys.view;


import br.com.ofiSys.model.entity.Cliente;
import br.com.ofiSys.model.entity.Veiculo;
import br.com.ofiSys.model.dao.DaoVeiculo;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author meritor
 */
public class GerenciarVeiculo extends javax.swing.JFrame {
    
    /**
     * Creates new form GerenciarVeiculo
     */
    
    
    public GerenciarVeiculo() {
        initComponents();
    }

    private Veiculo veic;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jButtonBuscarID = new javax.swing.JButton();
        jButtonBuscarPlaca = new javax.swing.JButton();
        jFormattedTextFieldCampoPlaca = new javax.swing.JFormattedTextField();
        jTextFieldCampoID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaConsultaVeiculos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 700, 20));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 20));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 700, 20));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 700, 10));

        jButtonBuscarID.setText("Buscar por ID");
        jButtonBuscarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarIDActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscarID, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        jButtonBuscarPlaca.setText("Buscar por placa");
        jButtonBuscarPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarPlacaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscarPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jFormattedTextFieldCampoPlaca.setPreferredSize(new java.awt.Dimension(100, 27));
        jFormattedTextFieldCampoPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCampoPlacaActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextFieldCampoPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 70, 30));

        jTextFieldCampoID.setPreferredSize(new java.awt.Dimension(30, 27));
        getContentPane().add(jTextFieldCampoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, 30));

        jButton1.setText("Remover veiculo");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, -1, -1));

        jButton2.setText("Cadastrar veiculo");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, -1));

        jButton3.setText("Editar veiculo");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, -1));

        tabelaConsultaVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID veiculo", "Placa", "Marca", "Modelo", "Ano", "Km", "Proprietario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaConsultaVeiculos.setColumnSelectionAllowed(true);
        tabelaConsultaVeiculos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelaConsultaVeiculos);
        tabelaConsultaVeiculos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaConsultaVeiculos.getColumnModel().getColumn(0).setResizable(false);
        tabelaConsultaVeiculos.getColumnModel().getColumn(1).setResizable(false);
        tabelaConsultaVeiculos.getColumnModel().getColumn(2).setResizable(false);
        tabelaConsultaVeiculos.getColumnModel().getColumn(3).setResizable(false);
        tabelaConsultaVeiculos.getColumnModel().getColumn(4).setResizable(false);
        tabelaConsultaVeiculos.getColumnModel().getColumn(5).setResizable(false);
        tabelaConsultaVeiculos.getColumnModel().getColumn(6).setResizable(false);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 680, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarIDActionPerformed
        // TODO add your handling code here:
        veic = new Veiculo();
        DaoVeiculo daoVeic = new DaoVeiculo();
        
        if(jTextFieldCampoID != null){
            veic = daoVeic.retrieveId(Long.parseLong(jTextFieldCampoID.getText()));        
            ArrayList <Veiculo>lista = new ArrayList<>();
            lista.add(veic);
            DefaultTableModel tableModel = (DefaultTableModel) tabelaConsultaVeiculos.getModel();
            tableModel.setRowCount(0);
        
            for(Veiculo veicTemp : lista){        
                tableModel.addRow(new Object[]{veicTemp.getId(),veicTemp.getPlaca(),
                veicTemp.getMarca(),veicTemp.getModelo(),veicTemp.getAno(),
                veicTemp.getKm(),veicTemp.getProprietario().toString().substring(20)});
            }
        
            tabelaConsultaVeiculos.setModel(tableModel);
        }        
        
    }//GEN-LAST:event_jButtonBuscarIDActionPerformed

    private void jButtonBuscarPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarPlacaActionPerformed
        // TODO add your handling code here:
        veic = new Veiculo();
        DaoVeiculo daoVeic = new DaoVeiculo();
                
        ArrayList <Veiculo>lista = (ArrayList <Veiculo>) daoVeic.retrievePlaca(jFormattedTextFieldCampoPlaca.getText());
        DefaultTableModel tableModel = (DefaultTableModel) tabelaConsultaVeiculos.getModel();
        tableModel.setRowCount(0);
        
        for(Veiculo veicTemp : lista){        
            tableModel.addRow(new Object[]{veicTemp.getId(),veicTemp.getPlaca(),veicTemp.getMarca(),veicTemp.getModelo(),veicTemp.getAno(),veicTemp.getKm(),veicTemp.getProprietario().toString().substring(20)});
        }
        
        tabelaConsultaVeiculos.setModel(tableModel);        
    }//GEN-LAST:event_jButtonBuscarPlacaActionPerformed

    private void jFormattedTextFieldCampoPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCampoPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCampoPlacaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarVeiculo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonBuscarID;
    private javax.swing.JButton jButtonBuscarPlaca;
    private javax.swing.JFormattedTextField jFormattedTextFieldCampoPlaca;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextFieldCampoID;
    private javax.swing.JTable tabelaConsultaVeiculos;
    // End of variables declaration//GEN-END:variables
}
